on:
  push:
    branches: main
  schedule:
    - cron: 0 8 * * *

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install Libcurl
        run: sudo apt-get install libcurl4-openssl-dev
        
      - name: Install Fribidi & HarfBuzz
        run: sudo apt-get install libharfbuzz-dev
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v3
        with:
          r-version: '4.3.3'
          dependencies: true

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
