on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Set R_LIBS_USER
        run: echo "R_LIBS_USER=${R_LIBS_USER:-$(R RHOME)/site-library}" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: quarto-packages-${{ hashFiles('depends.Rds') }}
          restore-keys: quarto-packages-

      - name: Verify cache restoration
        run: ls $R_LIBS_USER

  # Install Packages Manually
      # - name: Install R Packages
      #   run: |
      #     R -e 'install.packages("rmarkdown")'
      #     R -e 'install.packages("lubridate")'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
